#spring:
#  profiles:
#    active:
#      - dubbo
#  dubbo:
#    registry:
#      id: yp
#      protocol: zookeeper   # 必填 服务发现 注册中心支持的协议 包括 dubbo,multicast,zookeeper,redis 默认是zookeeper
#      address: 127.0.0.1    # 必填 服务发现 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port，不同集群的注册中心，请配置多个spring.dubbo.registry.标签 1.0.16以上版本
#      port: 2181            # 可选 服务发现 注册中心缺省端口，当address没有带端口时使用此端口做为缺省值 2.0.0以上版本
#      register: true
#    application:
#      name: d1money-provider
#    base-package: com.d1money.d1moneyservice.service
#    provider:
#      retries: -1
#      protocol: dubbo-jvm
#      registry: yp
#    protocol:
#      port: 20881
#      name: dubbo
#
#
